/**
 * Injects version + plan from package.json into static HTML files.
 *
 * Replaces {{VERSION}} and {{PLAN}} placeholders in:
 *   - public/penpot-companion-ui.html
 *   - tauri-bridge/index.html
 *   - tauri-bridge/dist/index.html
 *
 * Run: node scripts/inject-version.mjs
 * Called automatically during yarn build (see package.json scripts).
 */

import { readFileSync, writeFileSync } from "fs";
import { execSync } from "child_process";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

// Read package.json
const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf-8"));
const VERSION = pkg.version;
const PLAN = pkg.plan || "community";
const PLAN_DISPLAY = PLAN.charAt(0).toUpperCase() + PLAN.slice(1);

// Local/current-build id — shown only in non-production bundles.
// `version.ts` decides whether to display it (it is suppressed whenever
// the bundle is compiled with NODE_ENV=production, i.e. any next build).
function computeBuildId() {
  try {
    const sha = execSync("git rev-parse --short HEAD", { encoding: "utf-8" }).trim();
    return sha ? `local-${sha}` : "local-unknown";
  } catch {
    return "local-unknown";
  }
}
const BUILD = computeBuildId();

// Write version.generated.ts so @/lib/version imports a hardcoded string.
// This avoids caching issues with require('../../package.json') in Next.js/Turbopack.
const generatedPath = resolve(root, "src", "lib", "version.generated.ts");
const generated = `// Auto-generated by scripts/inject-version.mjs — do not edit manually.
export const VERSION: string = ${JSON.stringify(VERSION)};
export const PLAN: string = ${JSON.stringify(PLAN)};
export const BUILD: string = ${JSON.stringify(BUILD)};
`;
writeFileSync(generatedPath, generated, "utf-8");
console.log(`  ✔ src/lib/version.generated.ts → v${VERSION} ${PLAN_DISPLAY} (build: ${BUILD})`);

const files = [
  "README.md",
  "public/figma-companion-ui.html",
  "public/penpot-companion-ui.html",
  "tauri-bridge/index.html",
  "tauri-bridge/dist/index.html",
];

for (const file of files) {
  const path = resolve(root, file);
  try {
    let content = readFileSync(path, "utf-8");
    const original = content;

    content = content
      .replace(/\{\{VERSION\}\}/g, VERSION)
      .replace(/\{\{PLAN\}\}/g, PLAN_DISPLAY);

    // Also update any existing hardcoded v0.x.x tags
    content = content.replace(/v\d+\.\d+\.\d+(?:\s+\w+)?/g, `v${VERSION} ${PLAN_DISPLAY}`);

    // Update shield.io version badge in README (alt text + URL slug)
    const shieldVersionPattern = /(?:Version\s+|version-)\d+\.\d+\.\d+/g;
    content = content.replace(shieldVersionPattern, (match) => {
      if (match.startsWith('Version ')) return `Version ${VERSION}`;
      if (match.startsWith('version-')) return `version-${VERSION}`;
      return match;
    });

    if (content !== original) {
      writeFileSync(path, content, "utf-8");
      console.log(`  ✔ ${file} → v${VERSION} ${PLAN_DISPLAY}`);
    } else {
      console.log(`  ~ ${file} (no changes needed)`);
    }
  } catch {
    console.warn(`  ⚠ ${file} not found, skipping`);
  }
}

console.log(`\nVersion injected: v${VERSION} ${PLAN_DISPLAY}`);

// NOTE: public/penpot-manifest.json deliberately has NO "version" field.
// Penpot RC5 rejects non-default manifest versions ("invalid manifest
// version"), its plugins-runtime schema (zod) does not even define a version
// key, and its own parser defaults the version to 1 when absent — so any
// value other than a tiny int risks rejection and buys nothing. Plugin
// freshness is handled by the Cache-Control: no-store header on /penpot-*
// (vercel.json) plus Penpot re-fetching dev plugins on each run.
